import React from 'react'

import { Helmet } from 'react-helmet'

import './icons.css'

const Icons = (props) => {
  return (
    <div className="icons-container">
      <Helmet>
        <title>exported project</title>
      </Helmet>
      <div className="icons-icons">
        <img
          alt="Facebook1016"
          src="/playground_assets/facebook1016-ine4.svg"
          className="icons-facebook"
        />
        <img
          alt="Twitter1016"
          src="/playground_assets/twitter1016-rr8r.svg"
          className="icons-twitter"
        />
        <div className="icons-you-tube">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-bji6-200h.png"
            className="icons-box"
          />
          <div className="icons-logo">
            <img
              alt="SVG1I101"
              src="/playground_assets/svg1i101-hur7.svg"
              className="icons-svg1"
            />
            <img
              alt="SVG2I101"
              src="/playground_assets/svg2i101-0qg7q.svg"
              className="icons-svg2"
            />
          </div>
        </div>
        <div className="icons-instagram">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-0lp-200h.png"
            className="icons-box01"
          />
          <div className="icons-logo01">
            <img
              alt="SVG3I101"
              src="/playground_assets/svg3i101-7hbi.svg"
              className="icons-svg3"
            />
            <img
              alt="SVG2I101"
              src="/playground_assets/svg2i101-uc6b.svg"
              className="icons-svg201"
            />
            <img
              alt="SVG1I101"
              src="/playground_assets/svg1i101-s2zv.svg"
              className="icons-svg101"
            />
          </div>
        </div>
        <img
          alt="Telegram1016"
          src="/playground_assets/telegram1016-hioi.svg"
          className="icons-telegram"
        />
        <div className="icons-discord">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-cvay-200h.png"
            className="icons-box02"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-k72e.svg"
            className="icons-logo02"
          />
        </div>
        <div className="icons-whats-app">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-c3k-200h.png"
            className="icons-box03"
          />
          <div className="icons-logo03">
            <img
              alt="SVG2I101"
              src="/playground_assets/svg2i101-x8bm.svg"
              className="icons-svg202"
            />
            <img
              alt="SVG1I101"
              src="/playground_assets/svg1i101-xb2q.svg"
              className="icons-svg102"
            />
          </div>
        </div>
        <div className="icons-figma">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-kd3f-200h.png"
            className="icons-box04"
          />
          <div className="icons-logo04">
            <img
              alt="SVG5I101"
              src="/playground_assets/svg5i101-jqut.svg"
              className="icons-svg5"
            />
            <img
              alt="SVG4I101"
              src="/playground_assets/svg4i101-t9icp.svg"
              className="icons-svg4"
            />
            <img
              alt="SVG3I101"
              src="/playground_assets/svg3i101-1etq.svg"
              className="icons-svg31"
            />
            <img
              alt="SVG2I101"
              src="/playground_assets/svg2i101-ivbg.svg"
              className="icons-svg203"
            />
            <img
              alt="SVG1I101"
              src="/playground_assets/svg1i101-d6zb.svg"
              className="icons-svg103"
            />
          </div>
        </div>
        <div className="icons-sketch">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-gdp-200h.png"
            className="icons-box05"
          />
          <div className="icons-logo05">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-kcsh.svg"
              className="icons-path"
            />
            <img
              alt="SVG8I101"
              src="/playground_assets/svg8i101-30ul.svg"
              className="icons-svg8"
            />
            <img
              alt="SVG7I101"
              src="/playground_assets/svg7i101-j4xj.svg"
              className="icons-svg7"
            />
            <img
              alt="SVG6I101"
              src="/playground_assets/svg6i101-e9u.svg"
              className="icons-svg6"
            />
            <img
              alt="SVG5I101"
              src="/playground_assets/svg5i101-m6pm.svg"
              className="icons-svg51"
            />
            <img
              alt="SVG4I101"
              src="/playground_assets/svg4i101-jgeb.svg"
              className="icons-svg41"
            />
            <img
              alt="SVG3I101"
              src="/playground_assets/svg3i101-z95y.svg"
              className="icons-svg32"
            />
            <img
              alt="SVG2I101"
              src="/playground_assets/svg2i101-fdxn.svg"
              className="icons-svg204"
            />
            <img
              alt="SVG1I101"
              src="/playground_assets/svg1i101-4e3.svg"
              className="icons-svg104"
            />
          </div>
        </div>
        <div className="icons-wikipedia">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-r1w-200h.png"
            className="icons-box06"
          />
          <div className="icons-logo06">
            <div className="icons--left">
              <img
                alt="VI101"
                src="/playground_assets/vi101-6f2p.svg"
                className="icons-v"
              />
            </div>
            <div className="icons--right">
              <img
                alt="VI101"
                src="/playground_assets/vi101-0z1s.svg"
                className="icons-v1"
              />
            </div>
          </div>
        </div>
        <div className="icons-notion">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-okli-200h.png"
            className="icons-box07"
          />
          <div className="icons-logo07">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-g5yo.svg"
              className="icons-path001"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-x4on.svg"
              className="icons-shape"
            />
          </div>
        </div>
        <div className="icons-mastercard">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-eup-200h.png"
            className="icons-box08"
          />
          <div className="icons-logo08">
            <img
              alt="Fill1I101"
              src="/playground_assets/fill1i101-2xxu.svg"
              className="icons-fill1"
            />
            <img
              alt="Fill2I101"
              src="/playground_assets/fill2i101-gx9.svg"
              className="icons-fill2"
            />
            <img
              alt="Fill4I101"
              src="/playground_assets/fill4i101-txxm.svg"
              className="icons-fill4"
            />
          </div>
        </div>
        <div className="icons-visa">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-95ot-200h.png"
            className="icons-box09"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-h16.svg"
            className="icons-logo09"
          />
        </div>
        <img
          alt="Mcdonalds1016"
          src="/playground_assets/mcdonalds1016-bmx.svg"
          className="icons-mcdonalds"
        />
        <div className="icons-slack">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-xsec-200h.png"
            className="icons-box10"
          />
          <div className="icons-logo10">
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-1zq4.svg"
              className="icons-shape01"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-zgka.svg"
              className="icons-shape02"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-op4n.svg"
              className="icons-shape03"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-nza.svg"
              className="icons-shape04"
            />
          </div>
        </div>
        <div className="icons-trello">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-5yi4-200h.png"
            className="icons-box11"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-tvvi.svg"
            className="icons-logo11"
          />
        </div>
        <div className="icons-mailchimp">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-dao5-200h.png"
            className="icons-box12"
          />
          <div className="icons-group2">
            <div className="icons-group">
              <img
                alt="ShapeI101"
                src="/playground_assets/shapei101-6pox.svg"
                className="icons-shape05"
              />
              <img
                alt="ShapeI101"
                src="/playground_assets/shapei101-ed5.svg"
                className="icons-shape06"
              />
              <img
                alt="PathI101"
                src="/playground_assets/pathi101-vyu1.svg"
                className="icons-path002"
              />
            </div>
          </div>
        </div>
        <div className="icons-burger-king">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-bei-200h.png"
            className="icons-box13"
          />
          <div className="icons-logo12">
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-13vo.svg"
              className="icons-shape07"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-w63j.svg"
              className="icons-shape08"
            />
          </div>
        </div>
        <img
          alt="Tumblr1016"
          src="/playground_assets/tumblr1016-8cl.svg"
          className="icons-tumblr"
        />
        <div className="icons-in-vision">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-2i9q-200h.png"
            className="icons-box14"
          />
          <div className="icons-logo13">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-3tr.svg"
              className="icons-path003"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-0evam.svg"
              className="icons-path004"
            />
          </div>
        </div>
        <div className="icons-xd">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-oecl-200h.png"
            className="icons-box15"
          />
          <div className="icons-logo14">
            <img
              alt="SVG2I101"
              src="/playground_assets/svg2i101-x75r.svg"
              className="icons-svg205"
            />
            <img
              alt="SVG1I101"
              src="/playground_assets/svg1i101-7zud.svg"
              className="icons-svg105"
            />
          </div>
        </div>
        <div className="icons-creative-cloud">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-3h-200h.png"
            className="icons-box16"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-xpq8.svg"
            className="icons-logo15"
          />
        </div>
        <div className="icons-photoshop">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-qhms-200h.png"
            className="icons-box17"
          />
          <div className="icons-logo16">
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-eoop.svg"
              className="icons-shape09"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-ef3m.svg"
              className="icons-path005"
            />
          </div>
        </div>
        <div className="icons-premiere-pro">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-ar1o-200h.png"
            className="icons-box18"
          />
          <div className="icons-logo17">
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-djef.svg"
              className="icons-shape10"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-urhc.svg"
              className="icons-path006"
            />
          </div>
        </div>
        <div className="icons-after-effects">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-1mf-200h.png"
            className="icons-box19"
          />
          <div className="icons-ae">
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-nrow.svg"
              className="icons-shape11"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-d61e.svg"
              className="icons-shape12"
            />
          </div>
        </div>
        <div className="icons-illustrator">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-aqk8-200h.png"
            className="icons-box20"
          />
          <div className="icons-logo18">
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-e8k3.svg"
              className="icons-shape13"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-ya6b.svg"
              className="icons-shape14"
            />
          </div>
        </div>
        <div className="icons-adobe">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-94a7-200h.png"
            className="icons-box21"
          />
          <div className="icons-logo5">
            <div className="icons-logo4">
              <div className="icons-logo3">
                <div className="icons-logo2">
                  <div className="icons-logo19">
                    <img
                      alt="PathI101"
                      src="/playground_assets/pathi101-tuux.svg"
                      className="icons-path007"
                    />
                    <img
                      alt="PathI101"
                      src="/playground_assets/pathi101-vxml.svg"
                      className="icons-path008"
                    />
                    <img
                      alt="PathI101"
                      src="/playground_assets/pathi101-ly4q.svg"
                      className="icons-path009"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="icons-shutterstock">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-ub2j-200h.png"
            className="icons-box22"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-ec7d.svg"
            className="icons-logo20"
          />
        </div>
        <div className="icons-react">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-2rt-200h.png"
            className="icons-box23"
          />
          <div>
            <img
              alt="OvalI101"
              src="/playground_assets/ovali101-i00i-200h.png"
              className="icons-oval"
            />
            <img
              alt="OvalI101"
              src="/playground_assets/ovali101-bea.svg"
              className="icons-oval1"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-n602.svg"
              className="icons-shape15"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-776.svg"
              className="icons-shape16"
            />
          </div>
        </div>
        <img
          alt="Webflow1016"
          src="/playground_assets/webflow1016-e0h5.svg"
          className="icons-webflow"
        />
        <img
          alt="LitecoinLTC1016"
          src="/playground_assets/litecoinltc1016-3az.svg"
          className="icons-litecoin-ltc"
        />
        <div className="icons-uniswap-uni">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-trru-200h.png"
            className="icons-box24"
          />
          <div>
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-t22o.svg"
              className="icons-shape17"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-uyag.svg"
              className="icons-path010"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-iqdq.svg"
              className="icons-path011"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-fidl.svg"
              className="icons-path012"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-l9u.svg"
              className="icons-path013"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-2h4n.svg"
              className="icons-path014"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-4hvd.svg"
              className="icons-path015"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-no.svg"
              className="icons-path016"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-9kgm.svg"
              className="icons-shape18"
            />
          </div>
        </div>
        <div className="icons-ripple-xrp">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-y6a-200h.png"
            className="icons-box25"
          />
          <div className="icons-logo23">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-1je.svg"
              className="icons-path017"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-ccs.svg"
              className="icons-path018"
            />
          </div>
        </div>
        <div className="icons-cardano-ada">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-5jua-200h.png"
            className="icons-box26"
          />
          <div className="icons-logo24">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-in0i.svg"
              className="icons-path019"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-m5as.svg"
              className="icons-path020"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-9uco.svg"
              className="icons-path021"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-3wp9.svg"
              className="icons-path022"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-yol.svg"
              className="icons-path023"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-l0kb.svg"
              className="icons-path024"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-zxrf.svg"
              className="icons-path025"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-mm6j.svg"
              className="icons-path026"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-yk49.svg"
              className="icons-path027"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-pffa.svg"
              className="icons-path028"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-kuw.svg"
              className="icons-path029"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-7jz9.svg"
              className="icons-path030"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-58vk.svg"
              className="icons-path031"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-e6.svg"
              className="icons-path032"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-d02a.svg"
              className="icons-path033"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-4abgp.svg"
              className="icons-path034"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-dx1c.svg"
              className="icons-path035"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-4iga.svg"
              className="icons-path036"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-6vxr.svg"
              className="icons-path037"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-ge3h.svg"
              className="icons-path038"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-k3f.svg"
              className="icons-path039"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-u6fo.svg"
              className="icons-path040"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-f197.svg"
              className="icons-path041"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-sfdp.svg"
              className="icons-path042"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-o3e.svg"
              className="icons-path043"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-wm7s.svg"
              className="icons-path044"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-ykyp.svg"
              className="icons-path045"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-aw04.svg"
              className="icons-path046"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-o1k.svg"
              className="icons-path047"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-3bh.svg"
              className="icons-path048"
            />
          </div>
        </div>
        <img
          alt="Vimeo1016"
          src="/playground_assets/vimeo1016-bods.svg"
          className="icons-vimeo"
        />
        <img
          alt="UTorrent1016"
          src="/playground_assets/utorrent1016-pxyn.svg"
          className="icons--torrent"
        />
        <div className="icons-i-db">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-u63d-200h.png"
            className="icons-box27"
          />
          <div className="icons-logo25">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-i6ib.svg"
              className="icons-path049"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-1ec.svg"
              className="icons-path050"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-gk79.svg"
              className="icons-shape19"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-k9l9.svg"
              className="icons-shape20"
            />
          </div>
        </div>
        <div className="icons-kfc">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-l8ff-200h.png"
            className="icons-box28"
          />
          <div className="icons-logo26">
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-mj4.svg"
              className="icons-shape21"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-1nu.svg"
              className="icons-shape22"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-ilc8.svg"
              className="icons-shape23"
            />
          </div>
        </div>
        <div className="icons-acrobat">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-1hn6-200h.png"
            className="icons-box29"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-a7wu.svg"
            className="icons-logo27"
          />
        </div>
        <div className="icons-messenger">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-0lqq-200h.png"
            className="icons-box30"
          />
          <div className="icons-logo28">
            <img
              alt="CombinedShapeI101"
              src="/playground_assets/combinedshapei101-inbd.svg"
              className="icons-combined-shape"
            />
          </div>
        </div>
        <div className="icons-upwork">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-5kog-200h.png"
            className="icons-box31"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-wmqc.svg"
            className="icons-logo29"
          />
        </div>
        <div className="icons-metamask">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-c3w-200h.png"
            className="icons-box32"
          />
          <div className="icons-logo30">
            <img
              alt="SVG1I101"
              src="/playground_assets/svg1i101-qjjg.svg"
              className="icons-svg106"
            />
            <img
              alt="SVG2I101"
              src="/playground_assets/svg2i101-915l.svg"
              className="icons-svg206"
            />
            <img
              alt="SVG3I101"
              src="/playground_assets/svg3i101-1bs.svg"
              className="icons-svg33"
            />
            <img
              alt="SVG4I101"
              src="/playground_assets/svg4i101-bqn9.svg"
              className="icons-svg42"
            />
            <img
              alt="SVG5I101"
              src="/playground_assets/svg5i101-py1i.svg"
              className="icons-svg52"
            />
            <img
              alt="SVG6I101"
              src="/playground_assets/svg6i101-8zn.svg"
              className="icons-svg61"
            />
            <img
              alt="SVG7I101"
              src="/playground_assets/svg7i101-7yt9.svg"
              className="icons-svg71"
            />
            <img
              alt="SVG8I101"
              src="/playground_assets/svg8i101-3cmw.svg"
              className="icons-svg81"
            />
            <img
              alt="SVG9I101"
              src="/playground_assets/svg9i101-fggc.svg"
              className="icons-svg9"
            />
            <img
              alt="SVG10I101"
              src="/playground_assets/svg10i101-tkv.svg"
              className="icons-svg10"
            />
            <img
              alt="SVG11I101"
              src="/playground_assets/svg11i101-g7yp.svg"
              className="icons-svg11"
            />
            <img
              alt="SVG12I101"
              src="/playground_assets/svg12i101-kdh.svg"
              className="icons-svg12"
            />
            <img
              alt="SVG13I101"
              src="/playground_assets/svg13i101-omfq.svg"
              className="icons-svg13"
            />
            <img
              alt="SVG14I101"
              src="/playground_assets/svg14i101-5g02.svg"
              className="icons-svg14"
            />
            <img
              alt="SVG15I101"
              src="/playground_assets/svg15i101-uvws.svg"
              className="icons-svg15"
            />
            <img
              alt="SVG16I101"
              src="/playground_assets/svg16i101-c5r8.svg"
              className="icons-svg16"
            />
            <img
              alt="SVG17I101"
              src="/playground_assets/svg17i101-xt89.svg"
              className="icons-svg17"
            />
            <img
              alt="SVG18I101"
              src="/playground_assets/svg18i101-fu4j.svg"
              className="icons-svg18"
            />
            <img
              alt="SVG19I101"
              src="/playground_assets/svg19i101-l63.svg"
              className="icons-svg19"
            />
            <img
              alt="SVG20I101"
              src="/playground_assets/svg20i101-fqx5.svg"
              className="icons-svg20"
            />
            <img
              alt="SVG21I101"
              src="/playground_assets/svg21i101-sfss.svg"
              className="icons-svg21"
            />
            <img
              alt="SVG22I101"
              src="/playground_assets/svg22i101-v46i.svg"
              className="icons-svg22"
            />
            <img
              alt="SVG23I101"
              src="/playground_assets/svg23i101-b8jf.svg"
              className="icons-svg23"
            />
            <img
              alt="SVG24I101"
              src="/playground_assets/svg24i101-cpgj.svg"
              className="icons-svg24"
            />
            <img
              alt="SVG25I101"
              src="/playground_assets/svg25i101-knsh.svg"
              className="icons-svg25"
            />
            <img
              alt="SVG26I101"
              src="/playground_assets/svg26i101-xixa.svg"
              className="icons-svg26"
            />
            <img
              alt="SVG27I101"
              src="/playground_assets/svg27i101-k32.svg"
              className="icons-svg27"
            />
            <img
              alt="SVG28I101"
              src="/playground_assets/svg28i101-sq3o.svg"
              className="icons-svg28"
            />
            <img
              alt="SVG29I101"
              src="/playground_assets/svg29i101-wp1.svg"
              className="icons-svg29"
            />
          </div>
        </div>
        <img
          alt="Coinbase1016"
          src="/playground_assets/coinbase1016-vpjq.svg"
          className="icons-coinbase"
        />
        <div className="icons-walletconnect">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-5pte-200h.png"
            className="icons-box33"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-tcu7.svg"
            className="icons-logo31"
          />
        </div>
        <div className="icons-tesla">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-wjdl-200h.png"
            className="icons-box34"
          />
          <div className="icons-logo32">
            <img
              alt="SVG2I101"
              src="/playground_assets/svg2i101-ojgn.svg"
              className="icons-svg207"
            />
            <img
              alt="SVG1I101"
              src="/playground_assets/svg1i101-nbvn.svg"
              className="icons-svg107"
            />
          </div>
        </div>
        <div className="icons-dribbble">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-cg1q-200h.png"
            className="icons-box35"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-deqy.svg"
            className="icons-logo33"
          />
        </div>
        <div className="icons-dribbble2">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-3rcm-200h.png"
            className="icons-box36"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-zjig.svg"
            className="icons-logo34"
          />
        </div>
        <img
          alt="Behance1016"
          src="/playground_assets/behance1016-pfqc.svg"
          className="icons-behance"
        />
        <img
          alt="Dropbox1016"
          src="/playground_assets/dropbox1016-xize.svg"
          className="icons-dropbox"
        />
        <img
          alt="PayPal1016"
          src="/playground_assets/paypal1016-fzvh.svg"
          className="icons-pay-pal"
        />
        <div className="icons-uber">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-j8ew-200h.png"
            className="icons-box37"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-ih0c.svg"
            className="icons-logo35"
          />
        </div>
        <img
          alt="Pintrest1016"
          src="/playground_assets/pintrest1016-7ep.svg"
          className="icons-pintrest"
        />
        <img
          alt="Spotify1016"
          src="/playground_assets/spotify1016-y3vh.svg"
          className="icons-spotify"
        />
        <img
          alt="Snapchat1016"
          src="/playground_assets/snapchat1016-65nn.svg"
          className="icons-snapchat"
        />
        <img
          alt="Netflix1016"
          src="/playground_assets/netflix1016-sacd.svg"
          className="icons-netflix"
        />
        <div className="icons-amazon">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-0g3-200h.png"
            className="icons-box38"
          />
          <img
            alt="SVG2I101"
            src="/playground_assets/svg2i101-159z.svg"
            className="icons-svg208"
          />
          <img
            alt="SVG1I101"
            src="/playground_assets/svg1i101-nh5i.svg"
            className="icons-svg108"
          />
        </div>
        <div className="icons-ethereum-eth">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-gq6g-200h.png"
            className="icons-box39"
          />
          <div className="icons-logo36">
            <img
              alt="SVG6I101"
              src="/playground_assets/svg6i101-3ke.svg"
              className="icons-svg62"
            />
            <img
              alt="SVG5I101"
              src="/playground_assets/svg5i101-7ihr.svg"
              className="icons-svg53"
            />
            <img
              alt="SVG4I101"
              src="/playground_assets/svg4i101-dxud.svg"
              className="icons-svg43"
            />
            <img
              alt="SVG3I101"
              src="/playground_assets/svg3i101-rira.svg"
              className="icons-svg34"
            />
            <img
              alt="SVG2I101"
              src="/playground_assets/svg2i101-9ub.svg"
              className="icons-svg209"
            />
            <img
              alt="SVG1I101"
              src="/playground_assets/svg1i101-etsb.svg"
              className="icons-svg109"
            />
          </div>
        </div>
        <div className="icons-bitcoin">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-annj-200h.png"
            className="icons-box40"
          />
          <img
            alt="logoI101"
            src="/playground_assets/logoi101-qymi.svg"
            className="icons-logo37"
          />
        </div>
        <div className="icons-tether">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-nm6o-200h.png"
            className="icons-box41"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-9ip.svg"
            className="icons-logo38"
          />
        </div>
        <div className="icons-dogecoin">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-6dik-200h.png"
            className="icons-box42"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-u1z9.svg"
            className="icons-logo39"
          />
        </div>
        <div className="icons-shiba">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-0fa-200h.png"
            className="icons-box43"
          />
          <div className="icons-logo40">
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-hjyc.svg"
              className="icons-shape24"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-5op.svg"
              className="icons-path051"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-pf5.svg"
              className="icons-path052"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-w19p.svg"
              className="icons-shape25"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-u518.svg"
              className="icons-path053"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-zvjk.svg"
              className="icons-path054"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-vaza.svg"
              className="icons-path055"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-wiin.svg"
              className="icons-path056"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-9ydm.svg"
              className="icons-path057"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-t4ut.svg"
              className="icons-path058"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-r69l.svg"
              className="icons-path059"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-ui0d.svg"
              className="icons-path060"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-aq5.svg"
              className="icons-path061"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-6xce.svg"
              className="icons-path062"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-yuu.svg"
              className="icons-path063"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-7tk.svg"
              className="icons-path064"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-gv7.svg"
              className="icons-path065"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-hisd.svg"
              className="icons-path066"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-fs5.svg"
              className="icons-path067"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-81wm.svg"
              className="icons-path068"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-j9gb.svg"
              className="icons-path069"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-mlj7.svg"
              className="icons-path070"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-1c2s.svg"
              className="icons-path071"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-xsx9.svg"
              className="icons-path072"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-n6kl.svg"
              className="icons-path073"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-ab8.svg"
              className="icons-path074"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-2rm.svg"
              className="icons-path075"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-5evp.svg"
              className="icons-path076"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-rxdv.svg"
              className="icons-path077"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-gso.svg"
              className="icons-path078"
            />
          </div>
        </div>
        <div className="icons-solana">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-3sod-200h.png"
            className="icons-box44"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-k8ut.svg"
            className="icons-logo41"
          />
        </div>
        <div className="icons-gmail">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-s8ca-200h.png"
            className="icons-box45"
          />
          <div className="icons-logo42">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-j66te.svg"
              className="icons-path079"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-i6vq.svg"
              className="icons-path080"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-mtt8.svg"
              className="icons-path081"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-0n7.svg"
              className="icons-path082"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-9kms.svg"
              className="icons-path083"
            />
          </div>
        </div>
        <div className="icons-drive">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-we9l-200h.png"
            className="icons-box46"
          />
          <div className="icons-logo43">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-ohu.svg"
              className="icons-path084"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-9lt.svg"
              className="icons-path085"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-dfya.svg"
              className="icons-path086"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-t6k.svg"
              className="icons-path087"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-9s4.svg"
              className="icons-path088"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-b5uh.svg"
              className="icons-path089"
            />
          </div>
        </div>
        <img
          alt="SpaceX1016"
          src="/playground_assets/spacex1016-0hp.svg"
          className="icons-space-x"
        />
        <div className="icons-disney">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-s6o7-200h.png"
            className="icons-box47"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-65r.svg"
            className="icons-logo44"
          />
        </div>
        <div className="icons-microsoft">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-uj9p-200h.png"
            className="icons-box48"
          />
          <img
            alt="RectangleI101"
            src="/playground_assets/rectanglei101-dfj2c-200h.png"
            className="icons-rectangle"
          />
          <img
            alt="RectangleI101"
            src="/playground_assets/rectanglei101-f8ah-200h.png"
            className="icons-rectangle1"
          />
          <img
            alt="RectangleI101"
            src="/playground_assets/rectanglei101-ljla-200h.png"
            className="icons-rectangle2"
          />
          <img
            alt="RectangleI101"
            src="/playground_assets/rectanglei101-eyzj-200h.png"
            className="icons-rectangle3"
          />
        </div>
        <div className="icons-coca-cola">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-ivci-200h.png"
            className="icons-box49"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-rp1.svg"
            className="icons-logo45"
          />
        </div>
        <div className="icons-dc">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-31kp-200h.png"
            className="icons-box50"
          />
          <img
            alt="ShapeI101"
            src="/playground_assets/shapei101-kvsf.svg"
            className="icons-shape26"
          />
        </div>
        <div className="icons-hbo">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-mwff-200h.png"
            className="icons-box51"
          />
          <div className="icons-logo46">
            <img
              alt="Fill15I101"
              src="/playground_assets/fill15i101-ykc.svg"
              className="icons-fill15"
            />
            <img
              alt="Fill16I101"
              src="/playground_assets/fill16i101-573.svg"
              className="icons-fill16"
            />
            <img
              alt="Fill17I101"
              src="/playground_assets/fill17i101-5v05.svg"
              className="icons-fill17"
            />
          </div>
        </div>
        <div className="icons-vb">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-eu8q-200h.png"
            className="icons-box52"
          />
          <div className="icons-logo47">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-gc4p.svg"
              className="icons-path090"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-aq7q.svg"
              className="icons-path091"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-x90t.svg"
              className="icons-shape27"
            />
          </div>
        </div>
        <div className="icons-marvel">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-std8-200h.png"
            className="icons-box53"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-z1g.svg"
            className="icons-logo48"
          />
        </div>
        <div className="icons-fiverr">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-1lk5-200h.png"
            className="icons-box54"
          />
          <div className="icons-logo21 icons-logo21">
            <img
              alt="LogoI101"
              src="/playground_assets/logoi101-m33f.svg"
              className="icons-logo49"
            />
          </div>
        </div>
        <img
          alt="Linkedin1016"
          src="/playground_assets/linkedin1016-jcs.svg"
          className="icons-linkedin"
        />
        <div className="icons-starbucks">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-pskk-200h.png"
            className="icons-box55"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-8hq7.svg"
            className="icons-logo50"
          />
        </div>
        <div className="icons-cnn">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-9wgks-200h.png"
            className="icons-box56"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-mdqq.svg"
            className="icons-logo51"
          />
        </div>
        <img
          alt="PayPal21016"
          src="/playground_assets/paypal21016-xp3h.svg"
          className="icons-pay-pal2"
        />
        <img
          alt="Apple1016"
          src="/playground_assets/apple1016-6rhk.svg"
          className="icons-apple"
        />
        <div className="icons-play">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-l4k-200h.png"
            className="icons-box57"
          />
          <div className="icons-logo52">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-1gop.svg"
              className="icons-path092"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-look.svg"
              className="icons-path093"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-ok6o.svg"
              className="icons-path094"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-zwgm.svg"
              className="icons-path095"
            />
          </div>
        </div>
        <div className="icons-medium">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-4p54-200h.png"
            className="icons-box58"
          />
          <div className="icons-logo53">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-khl.svg"
              className="icons-path096"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-yrof.svg"
              className="icons-path097"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-7vf.svg"
              className="icons-path098"
            />
          </div>
        </div>
        <div className="icons-word-press">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-hlct-200h.png"
            className="icons-box59"
          />
          <div className="icons-logo22 icons-logo22">
            <img
              alt="LogoI101"
              src="/playground_assets/logoi101-nlii.svg"
              className="icons-logo54"
            />
          </div>
        </div>
        <img
          alt="GitHub1016"
          src="/playground_assets/github1016-abx9.svg"
          className="icons-git-hub"
        />
        <div className="icons-electronic-arts">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-eajm-200h.png"
            className="icons-box60"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-5hun.svg"
            className="icons-logo55"
          />
        </div>
        <div className="icons-steam">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-l40r-200h.png"
            className="icons-box61"
          />
          <div className="icons-logo56">
            <img
              alt="CombinedShapeI101"
              src="/playground_assets/combinedshapei101-9jq.svg"
              className="icons-combined-shape1"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-wml.svg"
              className="icons-path099"
            />
          </div>
        </div>
        <div className="icons-git-hub1">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-wl2s-200h.png"
            className="icons-box62"
          />
          <div className="icons-logo57">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-34.svg"
              className="icons-path100"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-yuz.svg"
              className="icons-path101"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-245q.svg"
              className="icons-shape28"
            />
          </div>
        </div>
        <div className="icons-blizzard">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-5jsfk-200h.png"
            className="icons-box63"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-jm.svg"
            className="icons-logo58"
          />
        </div>
        <div className="icons-battlenet">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-la2m-200h.png"
            className="icons-box64"
          />
          <img
            alt="LogoI101"
            src="/playground_assets/logoi101-ugm.svg"
            className="icons-logo59"
          />
        </div>
        <div className="icons-sound-cloud">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-1ixd-200h.png"
            className="icons-box65"
          />
          <img
            alt="CloudI101"
            src="/playground_assets/cloudi101-n65b.svg"
            className="icons-cloud"
          />
        </div>
        <div className="icons-reddit">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-cdsb-200h.png"
            className="icons-box66"
          />
          <div className="icons-logo60">
            <img
              alt="LogoI101"
              src="/playground_assets/logoi101-zsn.svg"
              className="icons-logo61"
            />
          </div>
        </div>
        <div className="icons-live-journal">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-h41c-200h.png"
            className="icons-box67"
          />
          <div className="icons-logo62">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-sv6.svg"
              className="icons-path102"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-81f2.svg"
              className="icons-path103"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-qn0s.svg"
              className="icons-path104"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-74mg.svg"
              className="icons-path105"
            />
          </div>
        </div>
        <div className="icons-google">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-m4q6-200h.png"
            className="icons-box68"
          />
          <div className="icons-logo63">
            <img
              alt="SVG1I101"
              src="/playground_assets/svg1i101-vp8s.svg"
              className="icons-svg110"
            />
            <img
              alt="SVG2I101"
              src="/playground_assets/svg2i101-4jrq.svg"
              className="icons-svg210"
            />
            <img
              alt="SVG3I101"
              src="/playground_assets/svg3i101-3jrt.svg"
              className="icons-svg35"
            />
            <img
              alt="SVG4I101"
              src="/playground_assets/svg4i101-1qec.svg"
              className="icons-svg44"
            />
          </div>
        </div>
        <div className="icons-lightroom">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-801l-200h.png"
            className="icons-box69"
          />
          <div className="icons-logo64">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-j6s.svg"
              className="icons-path106"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-lrw.svg"
              className="icons-path107"
            />
          </div>
        </div>
        <div className="icons-in-design">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-chhj-200h.png"
            className="icons-box70"
          />
          <div className="icons-logo65">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-892.svg"
              className="icons-path108"
            />
            <img
              alt="ShapeI101"
              src="/playground_assets/shapei101-h2d.svg"
              className="icons-shape29"
            />
          </div>
        </div>
        <div className="icons-us-coin-usdc">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-zl2m-200h.png"
            className="icons-box71"
          />
          <div className="icons-logo66">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-5dnc.svg"
              className="icons-path109"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-fb8.svg"
              className="icons-path110"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-ld25.svg"
              className="icons-path111"
            />
          </div>
        </div>
        <img
          alt="AvalancheAVAX1016"
          src="/playground_assets/avalancheavax1016-q8mt.svg"
          className="icons-avalanche-avax"
        />
        <div className="icons-pancake-swap-cake">
          <img
            alt="BoxI101"
            src="/playground_assets/boxi101-94og-200h.png"
            className="icons-box72"
          />
          <div className="icons-logo67">
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-5iue.svg"
              className="icons-path112"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-939e.svg"
              className="icons-path113"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-owsl.svg"
              className="icons-path114"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-qz9v.svg"
              className="icons-path115"
            />
            <img
              alt="PathI101"
              src="/playground_assets/pathi101-ybvg.svg"
              className="icons-path116"
            />
          </div>
        </div>
      </div>
    </div>
  )
}

export default Icons
